global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: woori-relay
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["woori-relay:8080"]
        labels:
          application: WooriRelay

  - job_name: callbot-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["callbot-gateway:8000"]
        labels:
          application: WooriCallbotGateway

  - job_name: fds-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["fds-gateway:8010"]
        labels:
          application: WooriFdsGateway

  - job_name: triton
    metrics_path: /metrics
    static_configs:
      - targets: ["triton:8001"]
        labels:
          application: WooriTritonMock
